[tool.poetry]
name = "streamlit-kurs"
version = "0.1.0"
description = ""
authors = ["SM"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
streamlit = "^1.41.1"
openai = "^1.65.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
